#define MOVESPEED_DATA_INDEX_PRIORITY 1
#define MOVESPEED_DATA_INDEX_FLAGS 2
#define MOVESPEED_DATA_INDEX_MULTIPLICATIVE_SLOWDOWN 3

#define MOVESPEED_DATA_INDEX_MAX 3
#define MOVESPEED_ID_SILICON_VTEC						"SILICON_VTEC"
#define MOVESPEED_ID_SHRUNK								"SHRINK_SPEED_MODIFIER"
#define MOVESPEED_ID_GROW								"GROWTH_SPEED_MODIFIER"
